server:
  port: 9000

spring:
  application:
    name: oauth2-server

  datasource:
    url: jdbc:postgres://localhost:5432/oauth
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info,configprops