server:
  port: 9000

spring:
  application:
    name: oauth2-server

  datasource:
    url: jdbc:mariadb://localhost:3306/oauth2
    username: vd
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info,configprops